Add simple check of exit status
Check the exit status of the actual command (ideal.exe/wrf.exe) and prints a message into the job output file reminding the user to look in the wrf log files in the corresponding run directory.

diff --git a/run_ideal_tc b/run_ideal_tc
--- a/run_ideal_tc
+++ b/run_ideal_tc
@@ -77,3 +77,11 @@ ulimit -s unlimited
 
 echo running with $PBS_NCPUS mpi ranks
 time mpirun -np $PBS_NCPUS -report-bindings $WRF_ROOT/$CASE/ideal.exe
+OUT=$?
+
+if [ $OUT -ne 0 ]; then
+    echo "Execution of ideal.exe exited with non-zero status"
+    echo "Check rsl.out and rsl.error in $RUNDIR"
+fi
+
+
diff --git a/run_wrf_tc b/run_wrf_tc
--- a/run_wrf_tc
+++ b/run_wrf_tc
@@ -78,3 +78,9 @@ ulimit -s unlimited
 
 echo running with $PBS_NCPUS mpi ranks
 time mpirun -np $PBS_NCPUS -report-bindings ./wrf.exe
+OUT=$?
+if [ $OUT -ne 0 ]; then
+   echo "Execution returned non-zero exit status"
+   echo "Check rsl.out and rsl.error files in $RUNDIR"
+fi
+
